global:
  evaluation_interval: 15s
  external_labels:
    monitor: example
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - labels:
      node_type: prometheus
  - targets:
    - localhost:9090
- job_name: cluster
  static_configs:
  - labels:
      cluster: KBK-HOME
      instance: KBK-HOME
      node_type: clusterip
    targets:
    - 192.168.100.5:9101
    - 192.168.100.5:9102
    - 192.168.100.5:9103
