global:
  evaluation_interval: 15s
  external_labels:
    monitor: example
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - labels:
      node_type: prometheus
  - targets:
    - localhost:9090

###Modify the following to suit your cluster. This example has a single anvil and a single DSX.    
- job_name: cluster
  static_configs:
  - labels:
      cluster: YOUR_CLUSTER_NAME
      instance: YOUR_CLUSTER_NAME
      node_type: clusterip
    targets:
    - N.N.N.N:9101
    - N.N.N.N:9102
    - N.N.N.N:9103
- job_name: anvil_nodes
  static_configs:
  - labels:
      cluster: YOUR_CLUSTER_NAME
      instance: anvil-1.FQDN
      node_type: anvil
    targets:
    - N.N.N.N:9100
- job_name: dsx_nodes
  static_configs:
  - labels:
      cluster: YOUR_CLUSTER_NAME
      instance: dsx-1.FQDN
      node_type: dsx
    targets:
    - N.N.N.N:9100
    - N.N.N.N:9105